export enum ActivityType {
    REGISTER = 'REGISTER',
    LOGIN = 'LOGIN',
    LOGOUT = 'LOGOUT',
    PROFILE_UPDATE = 'PROFILE_UPDATE',
    MATERIAL_UPLOAD = 'MATERIAL_UPLOAD',
    MATERIAL_DOWNLOAD = 'MATERIAL_DOWNLOAD',
    MATERIAL_COMMENT = 'MATERIAL_COMMENT',
    MATERIAL_STATUS_CHANGE = 'MATERIAL_STATUS_CHANGE',
    MATERIAL_DELETE = 'MATERIAL_DELETE',
    COMMENT_DELETE = 'COMMENT_DELETE',
    ACCOUNT_DELETE = 'ACCOUNT_DELETE',
}
